spring.application.name=codementor

langchain4j.anthropic.chat-model.api-key=${ANTHROPIC_API_KEY}
langchain4j.anthropic.chat-model.model-name=claude-haiku-4-5-20251001
langchain4j.anthropic.chat-model.max-tokens=1024
langchain4j.anthropic.chat-model.temperature=0.1

spring.datasource.url=jdbc:postgresql://localhost:5432/codementor
spring.datasource.username=codementor
spring.datasource.password=vini14192306@
spring.jpa.hibernate.ddl-auto=update